
name: Custom Actions

description: Ver qué hace

inputs:
  numOctocats:
    description: 'Number of Octocats'
    required: false
    default: '1'
  octocatEyeColor:
    description: 'Eye color of the Octocats'
    required: true

runs:
  using: node12
  main: 'main.js'

