# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  checkStyle:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: CheckStyle
      run: mvn checkstyle:checkstyle
    - name: Print the final result
      shell: bash
      run: |
        errors=$(cat target/checkstyle-result.xml | grep error | wc -l)
        echo Numbers of error = $errors
    #Tomar un caso por default si no existe el artefacto previo o no se encuentra
    - run: mkdir staging && cp target/checkstyle-result.xml staging
    - uses: actions/upload-artifact@v2
      with:
        name: checkstyle-result.xml
        path: staging



  #PMD:
  #  need: [build,checkStyle]
